# ansible notebook, to configure the VMs on GCP
- name: Create Compute Engine instances
  hosts: localhost
  gather_facts: no
  vars:
    gcp_project: sixth-wave-437406-n0
    gcp_cred_kind: serviceaccount
    gcp_cred_file: "/home/arturo/practica4/sixth-wave-437406-n0-fcbbbc47f3bf.json"  # Aqui setear con la ruta de vuestra SA
    region: "europe-west1"
    zone: "europe-west1-b"
    machine_type: "e2-medium"
    image: "projects/centos-cloud/global/images/centos-stream-9-v20240919"

  tasks:
    - name: Create private IP address to the VM instance
      gcp_compute_address:
        name: "maquina-prueba-ip"
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        service_account_file: "{{ gcp_cred_file }}"
        auth_kind: "{{ gcp_cred_kind }}"
      register: gce_ip

    - name: Bring up the instance in the zone
      gcp_compute_instance:
        name: "maquina-prueba"
        machine_type: "{{ machine_type }}"
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: "{{ image }}"
        network_interfaces:
          - access_configs:
              - name: External NAT
                nat_ip: "{{ gce_ip }}"
                type: ONE_TO_ONE_NAT
        tags:
          items:
            - http-server
            - https-server
            - ssh-externo
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        service_account_file: "{{ gcp_cred_file }}"
        auth_kind: "{{ gcp_cred_kind }}"
      register: gce

    - name: Create firewall rule for SSH (port 22)
      gcp_compute_firewall:
        name: "allow-ssh"
        allowed:
          - ip_protocol: tcp
            ports:
              - "22"
        source_ranges:
          - "0.0.0.0/0"
        target_tags:
          - "ssh-externo"
        project: "{{ gcp_project }}"
        service_account_file: "{{ gcp_cred_file }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: "present"

    - name: Create firewall rule for HTTP (port 80)
      gcp_compute_firewall:
        name: "allow-http"
        allowed:
          - ip_protocol: tcp
            ports:
              - "80"
        source_ranges:
          - "0.0.0.0/0"
        target_tags:
          - "http-server"
        project: "{{ gcp_project }}"
        service_account_file: "{{ gcp_cred_file }}"
        auth_kind: "{{ gcp_cred_kind }}"
        state: "present"

  post_tasks:
    - name: Save host data
      add_host:
        hostname: "{{ gce_ip.address }}"
        groups: gce_instances_ips

- name: Deploy httpd and custom html page
  hosts: gce_instances_ips
  become: yes   # run as root
  become_method: sudo
  roles:
    - simple-web
